spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/brandshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true

  security:
    user:
      name: user
      password: 1111

  jwt:
    secret: pepega52483285724012312314w23234324323535233
spring.jpa.properties.hibernate.use_sql_comments: true

spring.jackson.serialization.fail-on-empty-beans: false

logging.level:
  org.hibernate.SQL: debug



# org.hibernate.type: trace